### ISSUE TITLE
AWS server stuck at 100% for 7 hours

### ISSUE THREAD

**Issue by Just-a-Unity-Dev** [Kieaer/Essentials#102]
**How to reproduce**
1. Make a t2.micro AWS server
2. Install Mindustry and Java 17
3. `wget` the latest release

**Logs**
```
642.0 kB/642.0 kB-------[********************] 100%, ETA: 00:00:00
```

**Additional context**
Using the `JSEval` and the `Cargo Pods` mod

**Comment by Kieaer** [comment]
Try to ``java -Duser.language=en -Duser.country=US -jar server.jar`` to start server.
I'll look at this bug again.

**Comment by Just-a-Unity-Dev** [comment]
@Kieaer yep, your work around worked, but now I have the same issue as #101

**Comment by Just-a-Unity-Dev** [comment]
actually, not #101 but #103
