### ISSUE TITLE
How do i disable foo client blocking

### ISSUE THREAD

**Issue by quantum-brokengrammar** [Kieaer/Essentials#108]
How do i disable foo client blocking?

**Comment by Kieaer** [comment]
https://github.com/Kieaer/Essentials/wiki/Config-detail-information#blockfooclient

**Comment by quantum-brokengrammar** [comment]
ty

**Comment by quantum-brokengrammar** [comment]
I did it It shows up in the config that foo client blocking is disabled
however when i joined with foo client it still didnt work, it still blocked the foo client

**Comment by Kieaer** [comment]
Fixed Essentials 13.3
