### ISSUE TITLE
[suggestion] ChatEvent Using chatFormatter

### ISSUE THREAD

**Issue by Miniontoby** [Kieaer/Essentials#112]
Hi,

I would like to propose that you might just instead of using the PlayerChatEvent which cannot be 'stopped' using a different mod to just use the overridable `Vars.netServer.chatFormatter`.

If this won't be done, then I might not use this mod anymore, since I really need player ranks show up with chat messages!

Example for overriding `Vars.netServer.chatFormatter`:
```java
Vars.netServer.chatFormatter = (player, message) -> player == null ? message : "[gray]" + player.name + " [orange] > [white]" + message;
```

- Miniontoby

**Comment by Kieaer** [comment]
This feature created a bug in all features that use chat

**Comment by Kieaer** [comment]
What exactly does ``since I really need player ranks show up with chat messages!`` message mean?

**Comment by Miniontoby** [comment]
I just wanted to NOT USE the chat thing of this mod, but just my own custom one!
Since the `Vars.netServer.chatFormatter` is the correct way to change the format that's used for chat messages allowing you to override it, but the way this mod does the same job without that, I can't overwrite this one using a different mod. So I will have to find a way to disable the chat function or I will just turn off auto-update.

Or wait what?

**Comment by Kieaer** [comment]
No prob. It's already solved
