### ISSUE TITLE
[Question] Local Servers

### ISSUE THREAD

**Issue by C0D6WasTaken** [Kieaer/Essentials#122]
### Why am I asking this?
Each time I join, I get kicked with the message: `Kicking connection 0.0.0.0 / <UUID>; Reason: You're already logged!`

Can I join a locally hosted server from the same device hosting it? If yes, how? I haven't been able to find anything within the configuration file.

**Comment by Kieaer** [comment]
No. because the plugin complies with 1 device = 1 account.

If griefers are intentionally running multiple clients on one device, that player cannot be resolved by ban.
Basically, the Mindustry server already doesn't allow multiple devices, but being able to connect simultaneously means that this security device has been bypassed.

You can disable mindustry internal security system using `strict off` command in console.
But this plugin can't. use another device or run Github version + Steam version.

**Comment by C0D6WasTaken** [comment]
Thanks for the help! I managed to find a workaround by using a proxy. 

Also, I noticed that clients using the mod [Scheme Size](https://github.com/xzxADIxzx/Scheme-Size) cannot join the server. 
Do you perhaps know what is causing this issue?
```java
[E] arc.util.serialization.SerializationException: Unable to convert value to required type: fake (arc.struct.IntMap)
	at arc.util.serialization.Json.readValue(Json.java:1196)
	at arc.util.serialization.Json.readValue(Json.java:990)
	at arc.util.serialization.Json.fromJson(Json.java:831)
	at mindustry.io.JsonIO.read(JsonIO.java:61)
	at scheme.ServerIntegration.lambda$load$4(ServerIntegration.java:65)
	at mindustry.core.NetClient.clientPacketReliable(NetClient.java:154)
	at mindustry.gen.ClientPacketReliableCallPacket.handleClient(ClientPacketReliableCallPacket.java:36)
	at mindustry.net.Net.handleClientReceived(Net.java:293)
	at mindustry.net.ArcNetProvider$1.lambda$received$2(ArcNetProvider.java:83)
	at arc.util.TaskQueue.run(TaskQueue.java:17)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:194)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)
```
This is probably related to the client mod, but it's worth asking since its issue tracker isn't receiving much attention currently.

**Comment by Kieaer** [comment]
It was blocked because the mod name is not only increasing.
The mod contains code that allows or blocks the mode for certain servers only.
In addition, this mod can identify other players who use it, and this code is exactly the same as the modified client.

For allow this mod, you need disable anti-cheat config.

**Comment by Kieaer** [comment]
If you want increase max schematic size in anti-cheat enabled server, use this mod
https://github.com/Kieaer/Scheme-Size-Lite/releases/tag/V1.1

**Comment by C0D6WasTaken** [comment]
> To allow this mod, you need to disable the anti-cheat config.

One last question. How exactly? I can't seem to find anything inside the config.txt file that's related to this.
Thanks in advance!

**Comment by Kieaer** [comment]
Open config.txt file and find ``antiGrief: true``
set to ``antiGrief: false``

https://github.com/Kieaer/Essentials/wiki/Config-detail-information#antigrief

Config file will automatic reload if server is running

**Comment by C0D6WasTaken** [comment]
Even after disabling `antiGrief`, the error persists. I am referring to this:

> ```java
> [E] arc.util.serialization.SerializationException: Unable to convert value to required type: fake (arc.struct.IntMap)
> 	at arc.util.serialization.Json.readValue(Json.java:1196)
> 	at arc.util.serialization.Json.readValue(Json.java:990)
> 	at arc.util.serialization.Json.fromJson(Json.java:831)
> 	at mindustry.io.JsonIO.read(JsonIO.java:61)
> 	at scheme.ServerIntegration.lambda$load$4(ServerIntegration.java:65)
> 	at mindustry.core.NetClient.clientPacketReliable(NetClient.java:154)
> 	at mindustry.gen.ClientPacketReliableCallPacket.handleClient(ClientPacketReliableCallPacket.java:36)
> 	at mindustry.net.Net.handleClientReceived(Net.java:293)
> 	at mindustry.net.ArcNetProvider$1.lambda$received$2(ArcNetProvider.java:83)
> 	at arc.util.TaskQueue.run(TaskQueue.java:17)
> 	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:194)
> 	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
> 	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)
> ```

P.S. The default configuration was used for the server.

**Comment by Kieaer** [comment]
It's bug lol
download bug fixed version
https://github.com/Kieaer/Essentials/releases/tag/v18.1

**Comment by C0D6WasTaken** [comment]
LoL, aight
Thanks for the fix then :p
