### ISSUE TITLE
How setup database&

### ISSUE THREAD

**Issue by Egor00f** [Kieaer/Essentials#125]
idk

**Comment by Kieaer** [comment]
https://github.com/Kieaer/Essentials/releases/tag/v19
Read this patch note
You need install MySQL or PostgreSQL or MariaDB

Then create database using any sql tools
example
postgresql -> pgAdmin 4, mysql -> mysql workbench or cli, etc...

Then, set database property config from config/mods/Essentials/config.txt
https://github.com/Kieaer/Essentials/releases/tag/v19.1

example
database: mysql://127.0.0.1:3306/essentials
database: mariadb://127.0.0.1:3306/essentials
database: postgresql://127.0.0.1:5432/essentials

set your database username and password and restart server.

I will make it easier to set up later.

**Comment by Egor00f** [comment]
okay.
i installed postgresql, created user and role named mindustryserver and created database named essentials
but the server is still not working

**Comment by Kieaer** [comment]
Make sure set postgresql://127.0.0.1:5432/essentials
If still not work, upload error here

**Comment by Egor00f** [comment]
I figured it out and fixed the error. The problem was that I configured postgresql incorrectly.
@Kieaer you should add some information to the wiki about configuring sql.
