### ISSUE TITLE
Add Support for SQLite

### ISSUE THREAD

**Issue by makarasty** [Kieaer/Essentials#130]
Hello,

I would like to request the addition of SQLite support in future versions of the Essentials plugin. SQLite is widely used for lightweight database management, especially in smaller projects or environments where a full-fledged database server like MySQL or PostgreSQL is not required.

Adding SQLite support would:

1. Simplify setup for users who prefer not to manage a separate database server.
2. Reduce overhead in environments with low resource availability.
3. Offer a more accessible option for testing and development.

Thank you for considering this feature request. It would greatly enhance the flexibility and usability of the plugin.

**Comment by Kieaer** [comment]
It will be supported in a future version, but is not suitable for use with multiple servers.

**Comment by makarasty** [comment]
I've recently tested Essentials 18.2 across various environments, and it worked flawlessly on all of them. Specifically, I tested it on the following setups:

- Docker container (Pterodactyl) (`ghcr.io/pterodactyl/yolks:java_21`)
- Linux Ubuntu 22 (Java 21)
- Windows 10 (JDK 22)
- Windows 11 (JDK 21)
- Windows 11 Tiny (JDK 21)

Running the server on these operating systems did not cause any errors.

Given the stable performance, I would like to request the ability to use the SQLite database from Essentials 18.2 in newer versions of the plugin. This would facilitate a smoother upgrade process for users who are relying on SQLite for database management in their current setups.

**Comment by Kieaer** [comment]
In Essentials 19, h2 database is used instead of SQLite.
It was suitable for more complex operations, but I didn't know that H2 Database has a bug that causes DB corruption when working with multiple clients.

So the next version will use SQLite again. (and already applied)

**Comment by makarasty** [comment]
Thank you for the update! I'm really looking forward to the next version that reverts to SQLite. It's great to hear that the team is addressing the issue, and I can't wait to try out the new release

**Comment by Kieaer** [comment]
https://github.com/Kieaer/Essentials/releases/tag/v20
