### ISSUE TITLE
if you disable strict nickname checking in the config, it will still work until you change the nickname to any other

### ISSUE THREAD

**Issue by Remint32** [Kieaer/Essentials#29]

**Comment by Remint32** [comment]
@Kieaer write ~~me~~here, if you need more information/bug "not understandable"

**Comment by Kieaer** [comment]
@Remint32 Can't reproduced
Did you try ``realname: false``?

**Comment by Remint32** [comment]
@Kieaer 
1) `realname: true` is enabled On the server
2) *a New* player with name `Foo` goes on server
3) the Player exits and enters with the name `Bar`
4) As expected, it displays the name `Foo` instead of `Bar`
\*** Area of the bug ***
5) the server turns off `realname: false` and/or restart/`reload` command
6) a Player leaves the server and comes again WITHOUT CHANGING the name from `Bar`
7) Server, not despite 5) point, continues to display name of `Foo` have player
\* * * * * * *

This continues until the player does not change the nickname to any and goes again, then the bug disappears. After that, the 'Bar' nickname is displayed correctly.

**Comment by Remint32** [comment]
!reopen

**Comment by Kieaer** [comment]
@Remint32 Because the realname function changes the client value, the game must be restarted before it can be resolved.
