### ISSUE TITLE
[IMPORTANT] Make config 'only console output' for antigrief/blockdetect/alertdeposit features

### ISSUE THREAD

**Issue by Remint32** [Kieaer/Essentials#30]
```
# Turn this feature on to activate anti-grief against block place/break of each player.
# blockdetect is a function that notifies players when a any block config is changed.
# alertdeposit is a feature that notifies you when an item is picked up and put into another block.
# client-output outputs logs in addition to output to the console also in the game itself, if true
antigrief: true
blockdetect: true
alertdeposit: true
client-output: false
```

**Comment by Remint32** [comment]
Very much shits chat and prevents players, but I do not want to disable these features, because I need them

**Comment by Kieaer** [comment]
It's designed to let players know that the player does non-block destroy griefing.
example) Power node disconnect, Change sorter/unloader settings..
If plugin don't let players know, players won't know who did griefing.

To enable logging and antigrief, You can see all players activity log in /config/mods/Essentials/log folder.
