### ISSUE TITLE
Command for despawn of all entities on the map (excluding players)

### ISSUE THREAD

**Issue by Remint32** [Kieaer/Essentials#32]
Very useful when spawned a lot of Reapers and Eradicators and you need it quickly to remove them, instead of looking for an empty corner, to enable the sandbox mode (which players will certainly abuse) and undermine their by reactors.

**Comment by Kieaer** [comment]
~~It's impossible due to the limitations of game sources.~~

**Comment by Kieaer** [comment]
Possible at the expense of performance issues

**Comment by Kieaer** [comment]
![ezgif com-optimize](https://user-images.githubusercontent.com/44261958/70858124-c1ea1b80-1f3e-11ea-87f3-46bcb20fbc18.gif)
