### ISSUE TITLE
Switching from sqlite to SQL

### ISSUE THREAD

**Issue by TMFuzz** [Kieaer/Essentials#45]
I tried taking on a sql db rather than a local sqlite file. i had to find a program to convert sqlite to sql as the the mod did not create tables.

After i converted sqlite to sql and uploaded the tables.
starting the script gave this internal error

```
C:\Users\Skate\Desktop\game-server-stuff\mindustry-server>java -jar server.jar
[01-12-2020 | 11:50:00] [I] [EssentialConfig] Config file loaded!
[01-12-2020 | 11:50:00] [I] [EssentialPlayer] Database type: MariaDB/MySQL/PostgreSQL
[01-12-2020 | 11:50:00] [E] Internal error! - (conn=2320882) BLOB/TEXT column 'connserver' can't have a default value
[01-12-2020 | 11:50:01] [I] 1 mods loaded.
[01-12-2020 | 11:50:02] [I] Server loaded. Type 'help' for help.
[01-12-2020 | 11:50:02] [I] [EssentialClient] Checking plugin update...
[01-12-2020 | 11:50:02] [I] [EssentialClient] Current version is up to date.
```
![image](https://user-images.githubusercontent.com/3608771/72224718-5e99dc00-3532-11ea-8ff5-3be3d005c108.png)
![image](https://user-images.githubusercontent.com/3608771/72224729-75403300-3532-11ea-881b-65018d6101b9.png)

**Comment by Kieaer** [comment]
This is because SQL syntax differs between SQLite and MariaDB/MySQL/PostgreSQL.

This bug will be resolved by creating a SQLite <-> MariaDB/MySQL/PostgreSQL conversion from the plugin.

**Comment by TMFuzz** [comment]
should the mod auto make tables in a blank mysql db?

**Comment by Kieaer** [comment]
Plugin automatically create tables

**Comment by TMFuzz** [comment]
I wiped the sql db and all essential files except the config. I get an internal error. mindustry.players table not found. Do I have to manually make the table?
![image](https://user-images.githubusercontent.com/3608771/72451869-76ab6e80-3771-11ea-89b4-c5163354d822.png)

trying to join the server 
![image](https://user-images.githubusercontent.com/3608771/72452131-e4f03100-3771-11ea-8c2e-d105f6d4bf7b.png)

**Comment by Kieaer** [comment]
@FuzzyThor That's your DB Database not found problem
not table

**Comment by TMFuzz** [comment]
Maybe it has to do with using godaddy shared hosting mysql db.
It found the data prewipe. I found a program t convert sqlite to mysql uploaded the data to the db and was able to login with my perms but there are a lot of internal errors.

**Comment by Kieaer** [comment]
@FuzzyThor Upload error logs here
