### ISSUE TITLE
Game crashes trying to login from discord signup

### ISSUE THREAD

**Issue by TMFuzz** [Kieaer/Essentials#46]
the discord bot takes the password and clears the message. I joined the game with a bunch of alt codes on my name tried to login then the game crashed with a NullPointerException. I was just using sqlite in a linux server setting.
<details>
<summary>console copy&paste</summary>

> skater0guy@instance-2:~/games/mindustry$ ./run_server.sh
> [02-02-2020 | 15:42:54] [I] [EssentialConfig] Plugin language: English
> [02-02-2020 | 15:42:54] [I] [EssentialConfig] Config file loaded!
> [02-02-2020 | 15:42:54] [I] [EssentialPlayer] Database type: SQLite
> [02-02-2020 | 15:42:55] [I] 1 mods loaded.
> [02-02-2020 | 15:42:55] [I] Server loaded. Type 'help' for help.
> [02-02-2020 | 15:42:55] [I] [EssentialClient] Checking plugin update...
> [02-02-2020 | 15:42:55] [I] [EssentialClient] Current version is up to date.
> [02-02-2020 | 15:42:57] [I] [Essential] Discord service enabled!
> host
> [02-02-2020 | 15:43:40] [I] Randomized next map to be Wasteland.
> [02-02-2020 | 15:43:40] [I] Loading map...
> [02-02-2020 | 15:43:41] [I] Map loaded.
> [02-02-2020 | 15:43:41] [I] Opened a server on port 6567.
> [02-02-2020 | 15:44:18] [I] [0MXTgOo/AAA=] [LEVO]™ƒµžž has connected.
> [02-02-2020 | 15:48:16] [I] [EssentialPlayer] TMFuzz Player database created!
> [02-02-2020 | 15:49:15] [I] [0MXTgOo/AAA=] [LEVO]™ƒµžž has disconnected. (closed)
> [02-02-2020 | 15:49:20] [I] [0MXTgOo/AAA=] [LEVO]™ƒµžž has connected.
> [02-02-2020 | 15:49:34] [I] <[LEVO]™ƒµžž: /login buzz Buzz123!>
> [02-02-2020 | 15:49:34] [I] [0MXTgOo/AAA=] null has disconnected. (closed)
> [02-02-2020 | 15:49:54] [E] Internal error! - null
> [02-02-2020 | 15:50:01] [I] Game over! Reached wave 3 with 0 players online on map Wasteland.
> [02-02-2020 | 15:50:01] [I] Selected next map to be Islands.
> [02-02-2020 | 15:50:24] [E] Internal error! - null
> [02-02-2020 | 15:50:54] [E] Internal error! - null
> [02-02-2020 | 15:51:24] [E] Internal error! - null
> [02-02-2020 | 15:51:54] [E] Internal error! - null
> [02-02-2020 | 15:52:24] [E] Internal error! - null
> [02-02-2020 | 15:52:54] [E] Internal error! - null
> [02-02-2020 | 15:53:24] [E] Internal error! - null
> [02-02-2020 | 15:53:54] [E] Internal error! - null
> [02-02-2020 | 15:54:24] [E] Internal error! - null
> [02-02-2020 | 15:54:54] [E] Internal error! - null
> [02-02-2020 | 15:55:24] [E] Internal error! - null
> [02-02-2020 | 15:55:54] [E] Internal error! - null
> [02-02-2020 | 15:56:09] [I] Game over! Reached wave 2 with 0 players online on map Islands.

</details>
<details>
<summary>Game Crash log</summary>

> java.lang.NullPointerException
> 	at arc.graphics.g2d.GlyphLayout.setText(GlyphLayout.java:43)
> 	at mindustry.world.Block.drawPlaceText(Block.java:278)
> 	at mindustry.world.blocks.RespawnBlock.drawRespawn(RespawnBlock.java:70)
> 	at mindustry.world.blocks.storage.CoreBlock.drawLayer(CoreBlock.java:190)
> 	at mindustry.graphics.BlockRenderer.drawBlocks(BlockRenderer.java:285)
> 	at mindustry.core.Renderer.draw(Renderer.java:250)
> 	at mindustry.core.Renderer.update(Renderer.java:141)
> 	at arc.ApplicationCore.update(ApplicationCore.java:36)
> 	at mindustry.ClientLauncher.update(ClientLauncher.java:136)
> 	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:158)
> 	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:146)
> 	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:52)
> 	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:46)
> 

</details>

**Comment by Kieaer** [comment]
Need error.log from ``config/mods/Essentials/logs/`` folder

**Comment by TMFuzz** [comment]
[error.log](https://github.com/Kieaer/Essentials/files/4145691/error.log)

**Comment by Kieaer** [comment]
Did you tried 8.1.0? This bug has been already fixed.

**Comment by TMFuzz** [comment]
Yes i tried 8.1.0. I signed up on discord tried to log in using my phone. my game on the pc and phone crashed as soon as i submitted /login user pass

**Comment by TMFuzz** [comment]
I set it to ingame password made an account for owner
set it to discord made an account for my phone join login phone game crashed and so does the pc when the pc was logged in fine playing as owner since i made an ingame account seems as login in the game with an account from discord makes everyone crash. The server does not crash just the client. The server stays up.

**Comment by TMFuzz** [comment]
fuzzy was a bear

**Comment by LeoSko** [comment]
Just wanted to point out how I got such stacktrace with my own server plugin. I had been calling `Player::sendMessage` with null string, which caused client application to crash. Obvious fix: do not send null, but send some appropriate String (even empty one, but why?)
