### ISSUE TITLE
/event crashes the server or writes an long error.

### ISSUE THREAD

**Issue by RebornTrack970** [Kieaer/Essentials#59]
I really want to use /event beacuse it makes the server host 2 servers at the same time but it does not work.
it writes object not found, plugin error ...............
Can you help and tell me what i can do?

**Comment by RebornTrack970** [comment]
i wrote. /event host m fortress sandbox

**Comment by RebornTrack970** [comment]
Error:

Plugin internal error! - Not an object: [{"url":"https://api.github.com/repos/Kieaer/Essentials/releases/assets/17683264","id":17683264,"node_id":"MDEyOlJlbGVhc2VBc3NldDE3NjgzMjY0","name":"Essentials.jar","label":null,"uploader":{"login":"Kieaer","id":44261958,"node_id":"MDQ6VXNlcjQ0MjYxOTU4","avatar_url":"https://avatars1.githubusercontent.com/u/44261958?v=4","gravatar_id":"","url":"https://api.github.com/users/Kieaer","html_url":"https://github.com/Kieaer","followers_url":"https://api.github.com/users/Kieaer/followers","following_url":"https://api.github.com/users/Kieaer/following{/other_user}","gists_url":"https://api.github.com/users/Kieaer/gists{/gist_id}","starred_url":"https://api.github.com/users/Kieaer/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/Kieaer/subscriptions","organizations_url":"https://api.github.com/users/Kieaer/orgs","repos_url":"https://api.github.com/users/Kieaer/repos","events_url":"https://api.github.com/users/Kieaer/events{/privacy}","received_events_url":"https://api.github.com/users/Kieaer/received_events","type":"User","site_admin":false},"content_type":"application/java-archive","state":"uploaded","size":9924870,"download_count":114,"created_at":"2020-01-30T14:43:31Z","updated_at":"2020-01-30T14:43:45Z","browser_download_url":"https://github.com/Kieaer/Essentials/releases/download/8.1.0/Essentials.jar"}]

**Comment by Kieaer** [comment]
Duplicate https://github.com/Kieaer/Essentials/issues/58
