### ISSUE TITLE
cannot load the essentials 11

### ISSUE THREAD

**Issue by laok233** [Kieaer/Essentials#63]
**Describe the bug**
cannot load the plugin
**To Reproduce**

**Expected behavior**
fix the bug
**Screenshots**
![image](https://user-images.githubusercontent.com/72604018/96370948-e36bf300-115f-11eb-9827-0d7daece6ab7.png)
![image](https://user-images.githubusercontent.com/72604018/96370964-f252a580-115f-11eb-85d7-908b888cfb28.png)

**Server (please complete the following information):**
 - OS: Windows 7

**Additional context**

**Comment by Kieaer** [comment]
Essentials 11 is Mindustry 6.0 only
