### ISSUE TITLE
Java Recognise Error

### ISSUE THREAD

**Issue by RebornTrack970** [Kieaer/Essentials#65]
**Describe the bug**
idk, it says this:
java.lang.UnsupportedClassVersionError: essentials/Main has been compiled by a more recent version of the Java Runtime (class file version 58.0), this version of the Java Runtime only recognizes class file versions up to 52.0

**To Reproduce**
just open a server in 112.1 with latest version

**Expected behavior**

**Screenshots**

**Server (please complete the following information):**
 - Windows

**Additional context**

**Comment by Kieaer** [comment]
Try to use java 14
