### ISSUE TITLE
Server crash (as before and I re-open because is still there)

### ISSUE THREAD

**Issue by Xasmedy** [Kieaer/Essentials#68]
**Describe the bug**
The bug is the same as before the server crash when a block is placed, this time i tested with the last version that is the 11.3 but still.

**To Reproduce**
Place a block.

**Screenshots**
https://prnt.sc/vtw7dm

**Server (please complete the following information):**
Linux hosted server, mindustry version: v120, plugin version : 11.3

**Additional context**
I hope this can be fixed soon, for everything I'm available.

**Comment by pixecoz** [comment]
same problem.

**Comment by Xasmedy** [comment]
> same problem.

Developear said him will take time for fix, so we just need to wait.

**Comment by Kieaer** [comment]
@pixecoz @Xasmedy Try to use 11.4 version

**Comment by Kieaer** [comment]
Update to build 120.5 to solve this problem.
