### ISSUE TITLE
unable to compile

### ISSUE THREAD

**Issue by alexpvpmindustry** [Kieaer/Essentials#71]
**Describe the bug**
error is recieved when compiling with intellij

**To Reproduce**
1. set run config gradlew jar
2. run
3. error:

( this is the output with gradlew jar --info)
Microsoft Windows [Version 10.0.18362.657]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\Users\aktan\Documents\Essentials_alex>C:\Users\aktan\Documents\Essentials_alex\gradlew jar --info
Initialized native services in: C:\Users\aktan\.gradle\native
The client will now receive all logging from the daemon (pid: 18000). The daemon log file: C:\Users\aktan\.gradle\daemon\6.3\daemon-18000.out.log
Starting 3rd build in daemon [uptime: 5 mins 5.906 secs, performance: 100%, non-heap usage: 22% of 268.4 MB]
Using 4 worker leases.
Starting Build
Settings evaluated using settings file 'C:\Users\aktan\Documents\Essentials_alex\settings.gradle'.
Using local directory build cache for the root build (location = C:\Users\aktan\.gradle\caches\build-cache-1, removeUnusedEntriesAfter = 7 days).
Projects loaded. Root project using build file 'C:\Users\aktan\Documents\Essentials_alex\build.gradle'.
Included projects: [root project 'Essentials_alex']

> Configure project :
Evaluating root project 'Essentials_alex' using build file 'C:\Users\aktan\Documents\Essentials_alex\build.gradle'.
kotlin scripting plugin: created the scripting discovery configuration: kotlinScriptDef
kotlin scripting plugin: created the scripting discovery configuration: testKotlinScriptDef
All projects evaluated.
Selected primary task 'jar' from project :
Tasks to be executed: [task ':compileKotlin', task ':compileJava', task ':processResources', task ':classes', task ':inspectClassesForKotlinIC', task ':jar']
Tasks that were excluded: []
:compileKotlin (Thread[Execution worker for ':',5,main]) started.

> Task :compileKotlin
Build cache key for task ':compileKotlin' is ea94cdfa6e96bcf8bebfb8a2dd10f09f
Task ':compileKotlin' is not up-to-date because:
  Task has failed previously.
The input changes require a full rebuild for incremental task ':compileKotlin'.
file or directory 'C:\Users\aktan\Documents\Essentials_alex\src\main\java', not found
file or directory 'C:\Users\aktan\Documents\Essentials_alex\src\main\java', not found
file or directory 'C:\Users\aktan\Documents\Essentials_alex\src\main\java', not found
file or directory 'C:\Users\aktan\Documents\Essentials_alex\src\main\java', not found
Using Kotlin/JVM incremental compilation
i: found daemon on port 17244 (289521 ms old), trying to connect
i: connected to the daemon
Options for KOTLIN DAEMON: IncrementalCompilationOptions(super=CompilationOptions(compilerMode=INCREMENTAL_COMPILER, targetPlatform=JVM, reportCategories=[0], reportSeverity=2, requestedCompilationResults=[0]kotlinScriptExtensions=[
kt, kts, java]), areFileChangesKnown=false, modifiedFiles=null, deletedFiles=null, workingDir=C:\Users\aktan\Documents\Essentials_alex\build\kotlin\compileKotlin, multiModuleICSettings=MultiModuleICSettings(buildHistoryFile=C:\Users
\aktan\Documents\Essentials_alex\build\kotlin\compileKotlin\build-history.bin, useModuleDetection=false), usePreciseJavaTracking=trueoutputFiles=[C:\Users\aktan\Documents\Essentials_alex\build\classes\kotlin\main, C:\Users\aktan\Doc
uments\Essentials_alex\build\kotlin\compileKotlin])
e: C:\Users\aktan\Documents\Essentials_alex\src\main\kotlin\essentials\Main.kt: (17, 27): Unresolved reference: WebServer

> Task :compileKotlin FAILED
:compileKotlin (Thread[Execution worker for ':',5,main]) completed. Took 17.398 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 23s
1 actionable task: 1 execute

**Expected behavior**
A jar file should be generated

**Screenshots**

![image](https://user-images.githubusercontent.com/67626131/101662924-0abaae80-3a85-11eb-9ee3-551b6cb9c8fb.png)

version: 
IntelliJ IDEA 2020.2 (Community Edition)
Build #IC-202.6397.94, built on July 27, 2020
Runtime version: 11.0.7+10-b944.20 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1486M
Cores: 4
Non-Bundled Plugins: Key Promoter X, TunnelliJ, training, com.intellij.plugins.watcher, com.thvardhan.gradianto, org.jetbrains.kotlin, com.jetbrains.edu

**Comment by alexpvpmindustry** [comment]
sorry im noob ;-;

**Comment by Kieaer** [comment]
gradlew.bat jar
when intellij: https://www.jetbrains.com/help/idea/work-with-gradle-tasks.html#gradle_run_config

**Comment by alexpvpmindustry** [comment]
omg.. it compiles... 
![Uploading image.png…]()

**Comment by alexpvpmindustry** [comment]
![image](https://user-images.githubusercontent.com/67626131/101791130-22a23900-3b3e-11eb-8e52-5dd2bbfbb6b7.png)
