### ISSUE TITLE
plugin internal error

### ISSUE THREAD

**Issue by alexpvpmindustry** [Kieaer/Essentials#73]
**Describe the bug**
i think the plugin in throws this error when someone leaves the game

**To Reproduce**
1. start server with plugin
2. someone join
3. someone leaves
:ohno:

![image](https://user-images.githubusercontent.com/67626131/101909764-e97acf00-3bf8-11eb-9a9e-51d10e0b047b.png)

is there a way to catch this exception properly?
thank you. :)

**Comment by Kieaer** [comment]
Duplicate https://github.com/Kieaer/Essentials/issues/69
