### ISSUE TITLE
Command not working list

### ISSUE THREAD

**Issue by Kieaer** [Kieaer/Essentials#74]
- [x] players (arg problem)
- [ ] vote
- [x] All teleport command
- [x] spawn (Team not found)
- [x] tempban #84

**Comment by Kieaer** [comment]
* spawn (team not found)

**Comment by Kieaer** [comment]
* bundle - mob name mismatch

**Comment by alexpvpmindustry** [comment]
teleport commands dont work too, ttps ttpos etc

**Comment by ZetaMap** [comment]
Because doesn't exist in the code

**Comment by Kieaer** [comment]
@Susideur It worked the old way, but in the latest version of Mindustry it doesn't work due to network synchronization issues.

**Comment by ZetaMap** [comment]
ok
