### ISSUE TITLE
Servers not Working at all (atleast i think)

### ISSUE THREAD

**Issue by RebornTrack970** [Kieaer/Essentials#78]
**Describe the bug**
The cmd is empty, its pure black and i cant write anything.

**To Reproduce**
1. I just opened the plugin inside the mod file using openjdk than opened the runserver.bat

**Expected behavior**
I expected it to write atleast smth

**Screenshots**
![image](https://user-images.githubusercontent.com/62565267/102687981-8d213c00-4204-11eb-9aeb-d5c09a8c039e.png)

**Server (please complete the following information):**

**Additional context**
Pls help, idk whats happening.

**Comment by RebornTrack970** [comment]
should i wait?

**Comment by Kieaer** [comment]
Not a plugin error

**Comment by Kieaer** [comment]
Merge #79
