### ISSUE TITLE
Essentials doesn't load and give an error.

### ISSUE THREAD

**Issue by Xasmedy** [Kieaer/Essentials#83]
**Describe the bug**
Time I start the server in Windows 10 it get stuck as the previous issue I reported, but with the vps it doesn't load and give me an error and keep going without Essentials.
-Edit: At second try it worked. And now there's another error https://prnt.sc/wbkgif

**Screenshots**
https://prnt.sc/wbicg7

**Server (please complete the following information):**
OS: Windows 10 64bit & Debian 64bit, Mindustry: 122v, Essentials: 11.7

**Comment by Kieaer** [comment]
I think the file appears to be corrupt because it's not a common error.
Try downloading again.

**Comment by Xasmedy** [comment]
Probably yes was a file corruption but anyway, I got another error, this time fatal https://prnt.sc/wdaxqg

**Comment by Kieaer** [comment]
The first error occurs when the file is damaged and can't be extracted.
It may have been running or download/updating.

The second is a chat bug.
There's no way for users to fix it, so please wait for the bug patch.

**Comment by Kieaer** [comment]
Use Essentials 11.8 to solve this problem
