### ISSUE TITLE
 lobby on the server

### ISSUE THREAD

**Issue by uncaught1** [Kieaer/Essentials#85]
Hello, the /lobby command is mentioned in the plugin, and in the console it says "Lobby server functions are activated"
It's just not clear how to make a lobby world where you can choose which server to play on. Can you please tell me if there is such a possibility?

**Comment by uncaught1** [comment]
If it is not difficult for you, could you please leave detailed instructions on how to make a hub on the server?

**Comment by Kieaer** [comment]
Enter ``lobby`` command in the console.
This feature is disable normal players from modifying the map.

**Comment by Kieaer** [comment]
To create a moving zone between servers, you need to use the ``/warp`` command in game.
If you accidentally set the size of the zone incorrectly or you entered the server address incorrectly, use ``/reset <server address>`` in the console or in-game.

**Comment by Kieaer** [comment]
@uncaught1 To create warp block, use ``/warp block <server address>`` command. (must do it on top of that block)
This command will show players count and server description of the server will be displayed above the block.
