### ISSUE TITLE
I can't assign "groups" in the permission_user.json

### ISSUE THREAD

**Issue by Xasmedy** [Kieaer/Essentials#86]
**Describe the bug**
I can't give to a player a group (example "owner") and even if in the console it's writen that the permission file is updated, there's no difference. I'm not even sure if i can make a new group.

**Screenshots**
https://prnt.sc/we3w8z (console), https://prnt.sc/we3wev (permission_user)

**Server (please complete the following information):**
Debian 64bit, Mindustry: 122v, Essentials: 11.7

**Additional context**
Not sure if I did something wrong or it's a bug.

**Comment by Kieaer** [comment]
no problem.
Just use ``/help`` command to check owner's command
To enable admin mark, set to ``admin: true``

**Comment by Xasmedy** [comment]
Then the only problem is that I don't get the group prefix

**Comment by Kieaer** [comment]
Do you mean doesn't applying chat format?
check if the edited permission_user.hjson and your uuid are the same.
