### ISSUE TITLE
Essentials plugin: java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by ZetaMap** [Kieaer/Essentials#89]
**Describe the bug**
If the file name is "Essentials" the server don't start, but if just change the name (ex: "!Essentials") this error show.

**To Reproduce**
I just change the name of the file...

**Screenshots**
![Essencial error](https://user-images.githubusercontent.com/56844734/110015480-3071ef80-7d24-11eb-9974-9685ce6b565f.png)

**Server (please complete the following information):**
 - OS: Windows
 - server version: 125.1
 - plugin version: 11.8

**Comment by Kieaer** [comment]
Don't change plugin file name.
This error occurs because the plugin file can't be found when unzipping the file in the plugin file.

**Comment by ZetaMap** [comment]
ok
