### ISSUE TITLE
Can't add self as admin

### ISSUE THREAD

**Issue by TMFuzz** [Kieaer/Essentials#9]
Hello I am trying to configure this plugin but there are special characters in my name the show up as ?. I am also trying to use my id also to no avail. My steam name uses the alt code for TM but i cant add myself as admin. I was trying to open the player db but the db is locked.

**Comment by TMFuzz** [comment]
If it is relevant my full steam tag is [Clannameinbrackets]™username  i replaced my name to protect my identity but my steam name includes the square brackets [] and the trademark alt codes. Not sure if its related to a mod or game issue with my name convention.

**Comment by Kieaer** [comment]
@FuzzyThor This plug-in removes all the characters in [] and saves the nickname in the DB for nickname fixing and rainbow nickname functions.

Currently available solution is disable realname from ``config/plugins/Essentials/config``.
realname: true -> false

I will solve this problem soon.

**Comment by Kieaer** [comment]
fixed https://github.com/Kieaer/Essentials/commit/7b8af45a91d1a659cac7a24f07c4a77ff5860074
