### ISSUE TITLE
Not starting

### ISSUE THREAD

**Issue by GaviTSRA** [Kieaer/Essentials#90]
I put the plugin in the mods folder and started the server as normal (java -jar server.jar),
but it didn't load. I waited 10-15 minutes without any message appering in the terminal.
If i remove the mod, it startes normally in under a minute (with this message where the x are time and date: [xx-xx-xxxx xx:xx:xx] [I] Server loaded. Type 'help' for help.)

**Comment by Kieaer** [comment]
Try to ``java -Duser.language=en -Duser.country=US -jar server.jar``
There's an issue with the server not starting when running on a server in a language that the plugin doesn't currently support.

**Comment by ZetaMap** [comment]
so cool, thanks my server is finally starting correctly.

**Comment by Bertogim** [comment]
And if my host dosent allow me to change the startup command, i can do something?
