### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by ZetaMap** [Kieaer/Essentials#93]
Hello, I noticed in your code that you have a permission system with the chat that changes depending on the player's permissions. To do this you had to delete the base chat to be able to make your own. 
So my question is: how did you go about removing basic chat?

(translate by Google Translate)

**Comment by Kieaer** [comment]
https://github.com/Kieaer/Essentials/blob/master/src/main/kotlin/essentials/Main.kt#L154

**Comment by ZetaMap** [comment]
Thank you =)
