### ISSUE TITLE
help

### ISSUE THREAD

**Issue by imbirWIthSugar** [Kieaer/Essentials#94]
how to properly set up registration via discord?

    authType: discord
    discord: 
    {
      token: (mytoken)
    }

**Comment by Kieaer** [comment]
First, you must make own discord bot.
Go [Discord Developer Portal](https://discord.com/developers/applications) and make application.
![image](https://user-images.githubusercontent.com/44261958/120898644-b6287280-c666-11eb-8a97-51ada4e0a086.png)
and get bot token here.
You must invite the bot to your own Discord server after this.
and.. That's all! Send direct message to discord bot.

**Comment by imbirWIthSugar** [comment]
I know this, but I want to know how to write in the lines correctly:
authme:
and
discord:
because I have an error if I write true in the discord line

**Comment by Kieaer** [comment]
@iguxakak 
```
authType: "discord"
discord: {
   token: (your token)
}
```
If the error persists, please upload a stacktrace here.
