### ISSUE TITLE
/help not working

### ISSUE THREAD

**Issue by King-BR** [Kieaer/Essentials#95]
**Describe the bug**
When using Essentials plugin and trying to use the /help command the help message doesnt show up

**To Reproduce**
1. use /help
2. Help message doesnt show up as expected

**Expected behavior**
Show the help message

**Screenshots**
![image](https://user-images.githubusercontent.com/51011050/122693435-41316d00-d210-11eb-8606-06e786a49174.png)
![image](https://user-images.githubusercontent.com/51011050/122693457-54443d00-d210-11eb-8a49-04fd5f5dc453.png)

**Server (please complete the following information):**
 - OS:
 Windows datacenter 2019 (server host OS)
 Windows 10 (client OS)

**Additional context**
Doesnt show up anything in the error log (both from game and from plugin), double checked to see if the crash log was on but still didnt show up anything

Versions
![image](https://user-images.githubusercontent.com/51011050/122693727-7094a980-d211-11eb-9a51-d6f0bbc2652a.png)
![image](https://user-images.githubusercontent.com/51011050/122693744-8904c400-d211-11eb-96b9-3f109e9c178e.png)

**Comment by Kieaer** [comment]
Please upload permission.hjson file.

**Comment by King-BR** [comment]
sorry for the delay, here is the permission.hjson file
```hjson
{
  owner:
  {
    admin: true
    prefix: "[sky][Dono] %1[orange] > [white]%2"
    permission:
    [
      all
    ]
  }
  admin:
  {
    inheritance: user
    admin: true
    prefix: "[yellow][Admin] %1[orange] > [white]%2"
    permission:
    [
      color
      spawn
      weather
      kill
      team
      mute
    ]
  }
  user:
  {
    inheritance: visitor
    prefix: %1[orange] > [white]%2
    permission:
    [
      ch
      info
      maps
      me
      motd
      players
      status
      time
      tp
      vote
    ]
  }
  visitor:
  {
    prefix: %1[scarlet] > [white]%2
    default: true
    permission:
    [
      register
      login
      help
      t
    ]
  }
}
```
