### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by GergoEB** [Kieaer/Essentials#98]
**Describe the bug**

**To Reproduce**
5. go on fresh server and do /team

**Expected behavior**
i installed the plugin and did /team and it crashed me

**Screenshots**

**Server (please complete the following information):**
 - OS: Windows 10 Pro newest jdk 1.8.0

**Additional context**

**Comment by Kieaer** [comment]
Please write how to reproduced or upload console error log.
Problem not reproduced.

**Comment by Kieaer** [comment]
Closed due inactivity
