### ISSUE TITLE
And if my host dosent allow me to change the startup command, i can do something?

### ISSUE THREAD

**Issue by Bertogim** [Kieaer/Essentials#99]
#90

**Comment by Kieaer** [comment]
#90 already solved

**Comment by Bertogim** [comment]
Is a continuation of #90

**Comment by Bertogim** [comment]
They dont allow me to change the startup command, i can do something?

**Comment by Kieaer** [comment]
If you can access config.hjson, open config file and remove all texts, and write this
```
{
    settings: {
      language: "en_US"
    }
}
```

and start server.

**Comment by Bertogim** [comment]
i dont see the config.hjson on the plugin file

**Comment by Bertogim** [comment]
Yes, it creates files and folders, but I don't see config.hjson

<img width="430" alt="Screenshot_163" src="https://user-images.githubusercontent.com/91332073/146780556-d78fba26-c6fc-4513-b507-df72a6d5e365.png">

**Comment by Kieaer** [comment]
What's plugin version?

**Comment by Kieaer** [comment]
updated, you must __create__ ``config.hsjon`` file and write this
https://github.com/Kieaer/Essentials/issues/99#issuecomment-997939228
then save and load server.
